project: mmim_affection_base_trainval

program: main.py
name: baseline_hyper
method: grid
parameters:
  arch:
    values: [infomax]

  dataset:
    values: [udiva]
  cpc_layers:
    values: [2]

  dropout_prj: # 0.1 is not good
    values: [0.3]

  alpha:
    values: [0.3]

  sigma:
    values: [0.1] #sigma currently has no impact

  lr:
    values: [0.004]
  modalities:
    values: [ "text_facebody_audio"]
  wandb_mode:
    values: ["online"]
  scheduler:
    values: [ "constant"] #'multistep'] #,
  optimizer:
        values: ["lamb"]
  seed:
    values: [6, 1995, 1996]

  epochs:
    values: [30]

  is_baseline:
    values: [1]

  results_dir:
    values: ["/DATA/jj/affection/mmim_results/baseline"]

metric:
  goal: minimize
  name: test_loss








